### ISSUE TITLE
Integer flag support

### ISSUE THREAD

**Issue by djones** [oclif/parser#19]
Hi! I would like integer flags. I imagine the code on my command would look something like this:

```typescript
static flags = {
  port: flags.integer({
    char: 'p',
    description: 'port',
    default: 5001,
  }),
}

async run() {
  const { flags } = this.parse(Start)
  this.log(`x has started on port ${flags.port}`)
}
```

I did find reference to an integer here https://github.com/oclif/parser/blob/master/src/flags.ts#L70-L75 but I'm not sure how to use it. There is no type defined like so:
```typescript
export type IIntegerFlag<T> = IFlagBase<T, integer> & {}
```

**Comment by milesj** [comment]
+1

**Comment by djones** [comment]
Sweet, thanks @jdxcode!

**Comment by lqmanh** [comment]
Ok now we can use `flags.integer`. However, it doesn't seem to support `flags.float` or just simply `flags.number`. Will you implement these?
