### ISSUE TITLE
Flag gets picked up in place of missing arg

### ISSUE THREAD

**Issue by xavdid** [oclif/parser#57]
I've got the following command:

```js
class InitCommand extends Command {
  run() {
    const {flags, args} = this.parse(InitCommand);
    console.log('flags:', flags);
    console.log('args:', args);
  }
}

InitCommand.args = [
  {
    name: 'path',
    required: true,
    description:
      "Where to create the new app. If the directory doesn't exist, it will be created."
  }
];
```

And I invoke it with: `./bin/run init --blah`

### Expected Behavior

I would expect to see either (or both) of these errors:

1. `Error: Unexpected argument: --blah`
2. `Error: Missing 1 required arg: path`

 ### Actual Behavior

`--blah` is picked up as an arg, not a flag. So at run time, the path is invalid and the command isn't in "blah" mode.

```
flags: {} 
args: { path: '--blah' }
```

Is this a bug or intended behavior? If the former, I'm happy to fix it.

**Comment by MunifTanjim** [comment]
> "Arguments are positional arguments passed to the command." _ https://oclif.io/docs/args

So, whatever you pass as the first position will be picked up as `args.path`

This is intended behavior.

**Comment by RasPhilCo** [comment]
Correct. Though I get the trickiness of this situation, `--blah` _could be_ valid arg input. Or put another way, we have not made the parsing decision to say that it cannot be.

**Comment by xavdid** [comment]
Yeah that's fair. Ok, no worries!
